name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_gui.txt
    
    - name: Build executable
      run: |
        python build_executable.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Arkansas-Registry-Processor-Windows
        path: dist/
        retention-days: 30
    
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/Arkansas_Registry_Processor.exe
          dist/README.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 